"""add market_seasons table

Revision ID: 67d62df815c8
Revises: 3853f72ee731
Create Date: 2026-07-14 17:18:07.777594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d62df815c8'
down_revision: Union[str, None] = '3853f72ee731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(length=30), nullable=True),
    sa.Column('vix_score', sa.Float(), nullable=True),
    sa.Column('vix_rating', sa.String(length=30), nullable=True),
    sa.Column('put_call_score', sa.Float(), nullable=True),
    sa.Column('put_call_rating', sa.String(length=30), nullable=True),
    sa.Column('breadth_score', sa.Float(), nullable=True),
    sa.Column('breadth_rating', sa.String(length=30), nullable=True),
    sa.Column('social_bullish_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_seasons_fetched_at'), 'market_seasons', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_seasons_fetched_at'), table_name='market_seasons')
    op.drop_table('market_seasons')
    # ### end Alembic commands ###
