"""replace reddit tables with apewisdom trending snapshots

Revision ID: fa9d44ea0aa4
Revises: f2d902d1e44e
Create Date: 2026-07-11 01:15:50.581109

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa9d44ea0aa4'
down_revision: Union[str, None] = 'f2d902d1e44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('rank_24h_ago', sa.Integer(), nullable=True),
    sa.Column('mentions_24h_ago', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'source', 'fetched_at', name='uq_ticker_source_ts')
    )
    op.create_index('ix_trending_snapshots_fetched_at', 'trending_snapshots', ['fetched_at'], unique=False)
    op.create_index('ix_trending_snapshots_source', 'trending_snapshots', ['source'], unique=False)
    op.create_index('ix_trending_snapshots_ticker', 'trending_snapshots', ['ticker'], unique=False)
    op.drop_index(op.f('ix_stock_mentions_subreddit'), table_name='stock_mentions')
    op.drop_index(op.f('ix_stock_mentions_ticker'), table_name='stock_mentions')
    op.drop_table('stock_mentions')
    op.drop_index(op.f('ix_reddit_posts_reddit_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_subreddit'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reddit_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subreddit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('selftext', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_comments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reddit_posts_pkey'))
    )
    op.create_index(op.f('ix_reddit_posts_subreddit'), 'reddit_posts', ['subreddit'], unique=False)
    op.create_index(op.f('ix_reddit_posts_reddit_id'), 'reddit_posts', ['reddit_id'], unique=True)
    op.create_table('stock_mentions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subreddit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mentioned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('score', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_posts.id'], name=op.f('stock_mentions_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_mentions_pkey')),
    sa.UniqueConstraint('post_id', 'ticker', name=op.f('uq_post_ticker'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stock_mentions_ticker'), 'stock_mentions', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_mentions_subreddit'), 'stock_mentions', ['subreddit'], unique=False)
    op.drop_index('ix_trending_snapshots_ticker', table_name='trending_snapshots')
    op.drop_index('ix_trending_snapshots_source', table_name='trending_snapshots')
    op.drop_index('ix_trending_snapshots_fetched_at', table_name='trending_snapshots')
    op.drop_table('trending_snapshots')
    # ### end Alembic commands ###
